puts "Creating Aylien Categories......"

AylienCategory.create!(iab: "IAB1", category: "Arts & Entertainment")
AylienCategory.create!(iab: "IAB1-1", category: "Books & Literature")
AylienCategory.create!(iab: "IAB1-2", category: "Celebrity Fan/Gossip")
AylienCategory.create!(iab: "IAB1-3", category: "Fine Art")
AylienCategory.create!(iab: "IAB1-4", category: "Humor")
AylienCategory.create!(iab: "IAB1-5", category: "Movies")
AylienCategory.create!(iab: "IAB1-6", category: "Music")
AylienCategory.create!(iab: "IAB1-7", category: "Television")
AylienCategory.create!(iab: "IAB2", category: "Automotive")
AylienCategory.create!(iab: "IAB2-1", category: "Auto Parts")
AylienCategory.create!(iab: "IAB2-2", category: "Auto Repair")
AylienCategory.create!(iab: "IAB2-3", category: "Buying/Selling Cars")
AylienCategory.create!(iab: "IAB2-4", category: "Car Culture")
AylienCategory.create!(iab: "IAB2-5", category: "Certified Pre-Owned")
AylienCategory.create!(iab: "IAB2-6", category: "Convertible")
AylienCategory.create!(iab: "IAB2-7", category: "Coupe")
AylienCategory.create!(iab: "IAB2-8", category: "Crossover")
AylienCategory.create!(iab: "IAB2-9", category: "Diesel")
AylienCategory.create!(iab: "IAB2-10", category: "Electric Vehicle")
AylienCategory.create!(iab: "IAB2-11", category: "Hatchback")
AylienCategory.create!(iab: "IAB2-12", category: "Hybrid")
AylienCategory.create!(iab: "IAB2-13", category: "Luxury")
AylienCategory.create!(iab: "IAB2-14", category: "MiniVan")
AylienCategory.create!(iab: "IAB2-15", category: "Mororcycles")
AylienCategory.create!(iab: "IAB2-16", category: "Off-Road Vehicles")
AylienCategory.create!(iab: "IAB2-17", category: "Performance Vehicles")
AylienCategory.create!(iab: "IAB2-18", category: "Pickup")
AylienCategory.create!(iab: "IAB2-19", category: "Road-Side Assistance")
AylienCategory.create!(iab: "IAB2-20", category: "Sedan")
AylienCategory.create!(iab: "IAB2-21", category: "Trucks & Accessories")
AylienCategory.create!(iab: "IAB2-22", category: "Vintage Cars")
AylienCategory.create!(iab: "IAB2-23", category: "Wagon")
AylienCategory.create!(iab: "IAB3", category: "Business")
AylienCategory.create!(iab: "IAB3-1", category: "Advertising")
AylienCategory.create!(iab: "IAB3-2", category: "Agriculture")
AylienCategory.create!(iab: "IAB3-3", category: "Biotech/Biomedical")
AylienCategory.create!(iab: "IAB3-4", category: "Business Software")
AylienCategory.create!(iab: "IAB3-5", category: "Construction")
AylienCategory.create!(iab: "IAB3-6", category: "Forestry")
AylienCategory.create!(iab: "IAB3-7", category: "Government")
AylienCategory.create!(iab: "IAB3-8", category: "Green Solutions")
AylienCategory.create!(iab: "IAB3-9", category: "Human Resources")
AylienCategory.create!(iab: "IAB3-10", category: "Logistics")
AylienCategory.create!(iab: "IAB3-11", category: "Marketing")
AylienCategory.create!(iab: "IAB3-12", category: "Metals")
AylienCategory.create!(iab: "IAB4", category: "Careers")
AylienCategory.create!(iab: "IAB4-1", category: "Career Planning")
AylienCategory.create!(iab: "IAB4-2", category: "College")
AylienCategory.create!(iab: "IAB4-3", category: "Financial Aid")
AylienCategory.create!(iab: "IAB4-4", category: "Job Fairs")
AylienCategory.create!(iab: "IAB4-5", category: "Job Search")
AylienCategory.create!(iab: "IAB4-6", category: "Resume Writing/Advice")
AylienCategory.create!(iab: "IAB4-7", category: "Nursing")
AylienCategory.create!(iab: "IAB4-8", category: "Scholarships")
AylienCategory.create!(iab: "IAB4-9", category: "Telecommuting")
AylienCategory.create!(iab: "IAB4-10", category: "U.S. Military")
AylienCategory.create!(iab: "IAB4-11", category: "Career Advice")
AylienCategory.create!(iab: "IAB5", category: "Education")
AylienCategory.create!(iab: "IAB5-1", category: "7-12 Education")
AylienCategory.create!(iab: "IAB5-2", category: "Adult Education")
AylienCategory.create!(iab: "IAB5-3", category: "Art History")
AylienCategory.create!(iab: "IAB5-4", category: "Colledge Administration")
AylienCategory.create!(iab: "IAB5-5", category: "College Life")
AylienCategory.create!(iab: "IAB5-6", category: "Distance Learning")
AylienCategory.create!(iab: "IAB5-7", category: "English as a 2nd Language")
AylienCategory.create!(iab: "IAB5-8", category: "Language Learning")
AylienCategory.create!(iab: "IAB5-9", category: "Graduate School")
AylienCategory.create!(iab: "IAB5-10", category: "Homeschooling")
AylienCategory.create!(iab: "IAB5-11", category: "Homework/Study Tips")
AylienCategory.create!(iab: "IAB5-12", category: "K-6 Educators")
AylienCategory.create!(iab: "IAB5-13", category: "Private School")
AylienCategory.create!(iab: "IAB5-14", category: "Special Education")
AylienCategory.create!(iab: "IAB5-15", category: "Studying Business")
AylienCategory.create!(iab: "IAB6", category: "Family & Parenting")
AylienCategory.create!(iab: "IAB6-1", category: "Adoption")
AylienCategory.create!(iab: "IAB6-2", category: "Babies & Toddlers")
AylienCategory.create!(iab: "IAB6-3", category: "Daycare/Pre School")
AylienCategory.create!(iab: "IAB6-4", category: "Family Internet")
AylienCategory.create!(iab: "IAB6-5", category: "Parenting - K-6 Kids")
AylienCategory.create!(iab: "IAB6-6", category: "Parenting teens")
AylienCategory.create!(iab: "IAB6-7", category: "Pregnancy")
AylienCategory.create!(iab: "IAB6-8", category: "Special Needs Kids")
AylienCategory.create!(iab: "IAB6-9", category: "Eldercare")
AylienCategory.create!(iab: "IAB7", category: "Health & Fitness")
AylienCategory.create!(iab: "IAB7-1", category: "Exercise")
AylienCategory.create!(iab: "IAB7-2", category: "A.D.D.")
AylienCategory.create!(iab: "IAB7-3", category: "AIDS/HIV")
AylienCategory.create!(iab: "IAB7-4", category: "Allergies")
AylienCategory.create!(iab: "IAB7-5", category: "Alternative Medicine")
AylienCategory.create!(iab: "IAB7-6", category: "Arthritis")
AylienCategory.create!(iab: "IAB7-7", category: "Asthma")
AylienCategory.create!(iab: "IAB7-8", category: "Autism/PDD")
AylienCategory.create!(iab: "IAB7-9", category: "Bipolar Disorder")
AylienCategory.create!(iab: "IAB7-10", category: "Brain Tumor")
AylienCategory.create!(iab: "IAB7-11", category: "Cancer")
AylienCategory.create!(iab: "IAB7-12", category: "Cholesterol")
AylienCategory.create!(iab: "IAB7-13", category: "Chronic Fatigue Syndrome")
AylienCategory.create!(iab: "IAB7-14", category: "Chronic Pain")
AylienCategory.create!(iab: "IAB7-15", category: "Cold & Flu")
AylienCategory.create!(iab: "IAB7-16", category: "Deafness")
AylienCategory.create!(iab: "IAB7-17", category: "Dental Care")
AylienCategory.create!(iab: "IAB7-18", category: "Depression")
AylienCategory.create!(iab: "IAB7-19", category: "Dermatology")
AylienCategory.create!(iab: "IAB7-20", category: "Diabetes")
AylienCategory.create!(iab: "IAB7-21", category: "Epilepsy")
AylienCategory.create!(iab: "IAB7-22", category: "GERD/Acid Reflux")
AylienCategory.create!(iab: "IAB7-23", category: "Headaches/Migraines")
AylienCategory.create!(iab: "IAB7-24", category: "Heart Disease")
AylienCategory.create!(iab: "IAB7-25", category: "Herbs for Health")
AylienCategory.create!(iab: "IAB7-26", category: "Holistic Healing")
AylienCategory.create!(iab: "IAB7-27", category: "IBS/Crohn's Disease")
AylienCategory.create!(iab: "IAB7-28", category: "Incest/Abuse Support")
AylienCategory.create!(iab: "IAB7-29", category: "Incontinence")
AylienCategory.create!(iab: "IAB7-30", category: "Infertility")
AylienCategory.create!(iab: "IAB7-31", category: "Men's Health")
AylienCategory.create!(iab: "IAB7-32", category: "Nutrition")
AylienCategory.create!(iab: "IAB7-33", category: "Orthopedics")
AylienCategory.create!(iab: "IAB7-34", category: "Panic/Anxiety Disorders")
AylienCategory.create!(iab: "IAB7-35", category: "Pediatrics")
AylienCategory.create!(iab: "IAB7-36", category: "Physical Therapy")
AylienCategory.create!(iab: "IAB7-37", category: "Psychology/Psychiatry")
AylienCategory.create!(iab: "IAB7-38", category: "Senor Health")
AylienCategory.create!(iab: "IAB7-39", category: "Sexuality")
AylienCategory.create!(iab: "IAB7-40", category: "Sleep Disorders")
AylienCategory.create!(iab: "IAB7-41", category: "Smoking Cessation")
AylienCategory.create!(iab: "IAB7-42", category: "Substance Abuse")
AylienCategory.create!(iab: "IAB7-43", category: "Thyroid Disease")
AylienCategory.create!(iab: "IAB7-44", category: "Weight Loss")
AylienCategory.create!(iab: "IAB7-45", category: "Women's Health")
AylienCategory.create!(iab: "IAB8", category: "Food & Drink")
AylienCategory.create!(iab: "IAB8-1", category: "American Cuisine")
AylienCategory.create!(iab: "IAB8-2", category: "Barbecues & Grilling")
AylienCategory.create!(iab: "IAB8-3", category: "Cajun/Creole")
AylienCategory.create!(iab: "IAB8-4", category: "Chinese Cuisine")
AylienCategory.create!(iab: "IAB8-5", category: "Cocktails/Beer")
AylienCategory.create!(iab: "IAB8-6", category: "Coffee/Tea")
AylienCategory.create!(iab: "IAB8-7", category: "Cuisine-Specific")
AylienCategory.create!(iab: "IAB8-8", category: "Desserts & Baking")
AylienCategory.create!(iab: "IAB8-9", category: "Dining Out")
AylienCategory.create!(iab: "IAB8-10", category: "Food Allergies")
AylienCategory.create!(iab: "IAB8-11", category: "French Cuisine")
AylienCategory.create!(iab: "IAB8-12", category: "Health/Lowfat Cooking")
AylienCategory.create!(iab: "IAB8-13", category: "Italian Cuisine")
AylienCategory.create!(iab: "IAB8-14", category: "Japanese Cuisine")
AylienCategory.create!(iab: "IAB8-15", category: "Mexican Cuisine")
AylienCategory.create!(iab: "IAB8-16", category: "Vegan")
AylienCategory.create!(iab: "IAB8-17", category: "Vegetarian")
AylienCategory.create!(iab: "IAB8-18", category: "Wine")
AylienCategory.create!(iab: "IAB9", category: "Hobbies & Interests")
AylienCategory.create!(iab: "IAB9-1", category: "Art/Technology")
AylienCategory.create!(iab: "IAB9-2", category: "Arts & Crafts")
AylienCategory.create!(iab: "IAB9-3", category: "Beadwork")
AylienCategory.create!(iab: "IAB9-4", category: "Birdwatching")
AylienCategory.create!(iab: "IAB9-5", category: "Board Games/Puzzles")
AylienCategory.create!(iab: "IAB9-6", category: "Candle & Soap Making")
AylienCategory.create!(iab: "IAB9-7", category: "Card Games")
AylienCategory.create!(iab: "IAB9-8", category: "Chess")
AylienCategory.create!(iab: "IAB9-9", category: "Cigars")
AylienCategory.create!(iab: "IAB9-10", category: "Collecting")
AylienCategory.create!(iab: "IAB9-11", category: "Comic Books")
AylienCategory.create!(iab: "IAB9-12", category: "Drawing/Sketching")
AylienCategory.create!(iab: "IAB9-13", category: "Freelance Writing")
AylienCategory.create!(iab: "IAB9-14", category: "Genealogy")
AylienCategory.create!(iab: "IAB9-15", category: "Getting Published")
AylienCategory.create!(iab: "IAB9-16", category: "Guitar")
AylienCategory.create!(iab: "IAB9-17", category: "Home Recording")
AylienCategory.create!(iab: "IAB9-18", category: "Investors & Patents")
AylienCategory.create!(iab: "IAB9-19", category: "Jewelry Making")
AylienCategory.create!(iab: "IAB9-20", category: "Magic & Illusion")
AylienCategory.create!(iab: "IAB9-21", category: "Needlework")
AylienCategory.create!(iab: "IAB9-22", category: "Painting")
AylienCategory.create!(iab: "IAB9-23", category: "Photography")
AylienCategory.create!(iab: "IAB9-24", category: "Radio")
AylienCategory.create!(iab: "IAB9-25", category: "Roleplaying Games")
AylienCategory.create!(iab: "IAB9-26", category: "Sci-Fi & Fantasy")
AylienCategory.create!(iab: "IAB9-27", category: "Scrapbooking")
AylienCategory.create!(iab: "IAB9-28", category: "Screenwriting")
AylienCategory.create!(iab: "IAB9-29", category: "Stamps & Coins")
AylienCategory.create!(iab: "IAB9-30", category: "Video & Computer Games")
AylienCategory.create!(iab: "IAB9-31", category: "Woodworking")
AylienCategory.create!(iab: "IAB10", category: "Home & Garden")
AylienCategory.create!(iab: "IAB10-1", category: "Appliances")
AylienCategory.create!(iab: "IAB10-2", category: "Entertaining")
AylienCategory.create!(iab: "IAB10-3", category: "Environmental Safety")
AylienCategory.create!(iab: "IAB10-4", category: "Gardening")
AylienCategory.create!(iab: "IAB10-5", category: "Home Repair")
AylienCategory.create!(iab: "IAB10-6", category: "Home Theater")
AylienCategory.create!(iab: "IAB10-7", category: "Interior Decorating")
AylienCategory.create!(iab: "IAB10-8", category: "Landscaping")
AylienCategory.create!(iab: "IAB10-9", category: "Remodeling & Construction")
AylienCategory.create!(iab: "IAB11", category: "Law, Gov't & Politics")
AylienCategory.create!(iab: "IAB11-1", category: "Immigration")
AylienCategory.create!(iab: "IAB11-2", category: "Legal Issues")
AylienCategory.create!(iab: "IAB11-3", category: "U.S. Government Resources")
AylienCategory.create!(iab: "IAB11-4", category: "Politics")
AylienCategory.create!(iab: "IAB11-5", category: "Commentary")
AylienCategory.create!(iab: "IAB12", category: "News")
AylienCategory.create!(iab: "IAB12-1", category: "International News")
AylienCategory.create!(iab: "IAB12-2", category: "National News")
AylienCategory.create!(iab: "IAB12-3", category: "Local News")
AylienCategory.create!(iab: "IAB13", category: "Personal Finance")
AylienCategory.create!(iab: "IAB13-1", category: "Beginning Investing")
AylienCategory.create!(iab: "IAB13-2", category: "Credit/Debt & Loans")
AylienCategory.create!(iab: "IAB13-3", category: "Financial News")
AylienCategory.create!(iab: "IAB13-4", category: "Financial Planning")
AylienCategory.create!(iab: "IAB13-5", category: "Hedge Fund")
AylienCategory.create!(iab: "IAB13-6", category: "Insurance")
AylienCategory.create!(iab: "IAB13-7", category: "Investing")
AylienCategory.create!(iab: "IAB13-8", category: "Mutual Funds")
AylienCategory.create!(iab: "IAB13-9", category: "Options")
AylienCategory.create!(iab: "IAB13-10", category: "Retirement Planning")
AylienCategory.create!(iab: "IAB13-11", category: "Stocks")
AylienCategory.create!(iab: "IAB13-12", category: "Tax Planning")
AylienCategory.create!(iab: "IAB14", category: "Society")
AylienCategory.create!(iab: "IAB14-1", category: "Dating")
AylienCategory.create!(iab: "IAB14-2", category: "Divorce Support")
AylienCategory.create!(iab: "IAB14-3", category: "Gay Life")
AylienCategory.create!(iab: "IAB14-4", category: "Marriage")
AylienCategory.create!(iab: "IAB14-5", category: "Senior Living")
AylienCategory.create!(iab: "IAB14-6", category: "Teens")
AylienCategory.create!(iab: "IAB14-7", category: "Weddings")
AylienCategory.create!(iab: "IAB14-8", category: "Ethnic Specific")
AylienCategory.create!(iab: "IAB15", category: "Science")
AylienCategory.create!(iab: "IAB15-1", category: "Astrology")
AylienCategory.create!(iab: "IAB15-2", category: "Biology")
AylienCategory.create!(iab: "IAB15-3", category: "Chemistry")
AylienCategory.create!(iab: "IAB15-4", category: "Geology")
AylienCategory.create!(iab: "IAB15-5", category: "Paranormal Phenomena")
AylienCategory.create!(iab: "IAB15-6", category: "Physics")
AylienCategory.create!(iab: "IAB15-7", category: "Space/Astronomy")
AylienCategory.create!(iab: "IAB15-8", category: "Geography")
AylienCategory.create!(iab: "IAB15-9", category: "Botany")
AylienCategory.create!(iab: "IAB15-10", category: "Weather")
AylienCategory.create!(iab: "IAB16", category: "Pets")
AylienCategory.create!(iab: "IAB16-1", category: "Aquariums")
AylienCategory.create!(iab: "IAB16-2", category: "Birds")
AylienCategory.create!(iab: "IAB16-3", category: "Cats")
AylienCategory.create!(iab: "IAB16-4", category: "Dogs")
AylienCategory.create!(iab: "IAB16-5", category: "Large Animals")
AylienCategory.create!(iab: "IAB16-6", category: "Reptiles")
AylienCategory.create!(iab: "IAB16-7", category: "Veterinary Medicine")
AylienCategory.create!(iab: "IAB17", category: "Sports")
AylienCategory.create!(iab: "IAB17-1", category: "Auto Racing")
AylienCategory.create!(iab: "IAB17-2", category: "Baseball")
AylienCategory.create!(iab: "IAB17-3", category: "Bicycling")
AylienCategory.create!(iab: "IAB17-4", category: "Bodybuilding")
AylienCategory.create!(iab: "IAB17-5", category: "Boxing")
AylienCategory.create!(iab: "IAB17-6", category: "Canoeing/Kayaking")
AylienCategory.create!(iab: "IAB17-7", category: "Cheerleading")
AylienCategory.create!(iab: "IAB17-8", category: "Climbing")
AylienCategory.create!(iab: "IAB17-9", category: "Cricket")
AylienCategory.create!(iab: "IAB17-10", category: "Figure Skating")
AylienCategory.create!(iab: "IAB17-11", category: "Fly Fishing")
AylienCategory.create!(iab: "IAB17-12", category: "Football")
AylienCategory.create!(iab: "IAB17-13", category: "Freshwater Fishing")
AylienCategory.create!(iab: "IAB17-14", category: "Game & Fish")
AylienCategory.create!(iab: "IAB17-15", category: "Golf")
AylienCategory.create!(iab: "IAB17-16", category: "Horse Racing")
AylienCategory.create!(iab: "IAB17-17", category: "Horses")
AylienCategory.create!(iab: "IAB17-18", category: "Hunting/Shooting")
AylienCategory.create!(iab: "IAB17-19", category: "Inline Skating")
AylienCategory.create!(iab: "IAB17-20", category: "Martial Arts")
AylienCategory.create!(iab: "IAB17-21", category: "Mountain Biking")
AylienCategory.create!(iab: "IAB17-22", category: "NASCAR Racing")
AylienCategory.create!(iab: "IAB17-23", category: "Olympics")
AylienCategory.create!(iab: "IAB17-24", category: "Paintball")
AylienCategory.create!(iab: "IAB17-25", category: "Power & Motorcycles")
AylienCategory.create!(iab: "IAB17-26", category: "Pro Basketball")
AylienCategory.create!(iab: "IAB17-27", category: "Pro Ice Hockey")
AylienCategory.create!(iab: "IAB17-28", category: "Rodeo")
AylienCategory.create!(iab: "IAB17-29", category: "Rugby")
AylienCategory.create!(iab: "IAB17-30", category: "Running/Jogging")
AylienCategory.create!(iab: "IAB17-31", category: "Sailing")
AylienCategory.create!(iab: "IAB17-32", category: "Saltwater Fishing")
AylienCategory.create!(iab: "IAB17-33", category: "Scuba Diving")
AylienCategory.create!(iab: "IAB17-34", category: "Skateboarding")
AylienCategory.create!(iab: "IAB17-35", category: "Skiing")
AylienCategory.create!(iab: "IAB17-36", category: "Snowboarding")
AylienCategory.create!(iab: "IAB17-37", category: "Surfing/Bodyboarding")
AylienCategory.create!(iab: "IAB17-38", category: "Swimming")
AylienCategory.create!(iab: "IAB17-39", category: "Table Tennis/Ping-Pong")
AylienCategory.create!(iab: "IAB17-40", category: "Tennis")
AylienCategory.create!(iab: "IAB17-41", category: "Volleyball")
AylienCategory.create!(iab: "IAB17-42", category: "Walking")
AylienCategory.create!(iab: "IAB17-43", category: "Waterski/Wakeboard")
AylienCategory.create!(iab: "IAB17-44", category: "World Soccer")
AylienCategory.create!(iab: "IAB18", category: "Style & Fashion")
AylienCategory.create!(iab: "IAB18-1", category: "Beauty")
AylienCategory.create!(iab: "IAB18-2", category: "Body Art")
AylienCategory.create!(iab: "IAB18-3", category: "Fashion")
AylienCategory.create!(iab: "IAB18-4", category: "Jewelry")
AylienCategory.create!(iab: "IAB18-5", category: "Clothing")
AylienCategory.create!(iab: "IAB18-6", category: "Accessories")
AylienCategory.create!(iab: "IAB19", category: "Technology & Computing")
AylienCategory.create!(iab: "IAB19-1", category: "3-D Graphics")
AylienCategory.create!(iab: "IAB19-2", category: "Animation")
AylienCategory.create!(iab: "IAB19-3", category: "Antivirus Software")
AylienCategory.create!(iab: "IAB19-4", category: "C/C++")
AylienCategory.create!(iab: "IAB19-5", category: "Cameras & Camcorders")
AylienCategory.create!(iab: "IAB19-6", category: "Cell Phones")
AylienCategory.create!(iab: "IAB19-7", category: "Computer Certification")
AylienCategory.create!(iab: "IAB19-8", category: "Computer Networking")
AylienCategory.create!(iab: "IAB19-9", category: "Computer Peripherals")
AylienCategory.create!(iab: "IAB19-10", category: "Computer Reviews")
AylienCategory.create!(iab: "IAB19-11", category: "Data Centers")
AylienCategory.create!(iab: "IAB19-12", category: "Databases")
AylienCategory.create!(iab: "IAB19-13", category: "Desktop Publishing")
AylienCategory.create!(iab: "IAB19-14", category: "Desktop Video")
AylienCategory.create!(iab: "IAB19-15", category: "Email")
AylienCategory.create!(iab: "IAB19-16", category: "Graphics Software")
AylienCategory.create!(iab: "IAB19-17", category: "Home Video/DVD")
AylienCategory.create!(iab: "IAB19-18", category: "Internet Technology")
AylienCategory.create!(iab: "IAB19-19", category: "Java")
AylienCategory.create!(iab: "IAB19-20", category: "JavaScript")
AylienCategory.create!(iab: "IAB19-21", category: "Mac Support")
AylienCategory.create!(iab: "IAB19-22", category: "MP3/MIDI")
AylienCategory.create!(iab: "IAB19-23", category: "Net Conferencing")
AylienCategory.create!(iab: "IAB19-24", category: "Net for Beginners")
AylienCategory.create!(iab: "IAB19-25", category: "Network Security")
AylienCategory.create!(iab: "IAB19-26", category: "Palmtops/PDAs")
AylienCategory.create!(iab: "IAB19-27", category: "PC Support")
AylienCategory.create!(iab: "IAB19-28", category: "Portable")
AylienCategory.create!(iab: "IAB19-29", category: "Entertainment")
AylienCategory.create!(iab: "IAB19-30", category: "Shareware/Freeware")
AylienCategory.create!(iab: "IAB19-31", category: "Unix")
AylienCategory.create!(iab: "IAB19-32", category: "Visual Basic")
AylienCategory.create!(iab: "IAB19-33", category: "Web Clip Art")
AylienCategory.create!(iab: "IAB19-34", category: "Web Design/HTML")
AylienCategory.create!(iab: "IAB19-35", category: "Web Search")
AylienCategory.create!(iab: "IAB19-36", category: "Windows")
AylienCategory.create!(iab: "IAB20", category: "Travel")
AylienCategory.create!(iab: "IAB20-1", category: "Adventure Travel")
AylienCategory.create!(iab: "IAB20-2", category: "Africa")
AylienCategory.create!(iab: "IAB20-3", category: "Air Travel")
AylienCategory.create!(iab: "IAB20-4", category: "Australia & New Zealand")
AylienCategory.create!(iab: "IAB20-5", category: "Bed & Breakfasts")
AylienCategory.create!(iab: "IAB20-6", category: "Budget Travel")
AylienCategory.create!(iab: "IAB20-7", category: "Business Travel")
AylienCategory.create!(iab: "IAB20-8", category: "By US Locale")
AylienCategory.create!(iab: "IAB20-9", category: "Camping")
AylienCategory.create!(iab: "IAB20-10", category: "Canada")
AylienCategory.create!(iab: "IAB20-11", category: "Caribbean")
AylienCategory.create!(iab: "IAB20-12", category: "Cruises")
AylienCategory.create!(iab: "IAB20-13", category: "Eastern Europe")
AylienCategory.create!(iab: "IAB20-14", category: "Europe")
AylienCategory.create!(iab: "IAB20-15", category: "France")
AylienCategory.create!(iab: "IAB20-16", category: "Greece")
AylienCategory.create!(iab: "IAB20-17", category: "Honeymoons/Getaways")
AylienCategory.create!(iab: "IAB20-18", category: "Hotels")
AylienCategory.create!(iab: "IAB20-19", category: "Italy")
AylienCategory.create!(iab: "IAB20-20", category: "Japan")
AylienCategory.create!(iab: "IAB20-21", category: "Mexico & Central America")
AylienCategory.create!(iab: "IAB20-22", category: "National Parks")
AylienCategory.create!(iab: "IAB20-23", category: "South America")
AylienCategory.create!(iab: "IAB20-24", category: "Spas")
AylienCategory.create!(iab: "IAB20-25", category: "Theme Parks")
AylienCategory.create!(iab: "IAB20-26", category: "Traveling with Kids")
AylienCategory.create!(iab: "IAB20-27", category: "United Kingdom")
AylienCategory.create!(iab: "IAB21", category: "Real Estate")
AylienCategory.create!(iab: "IAB21-1", category: "Apartments")
AylienCategory.create!(iab: "IAB21-2", category: "Architects")
AylienCategory.create!(iab: "IAB21-3", category: "Buying/Selling Homes")
AylienCategory.create!(iab: "IAB22", category: "Shopping")
AylienCategory.create!(iab: "IAB22-1", category: "Contests & Freebies")
AylienCategory.create!(iab: "IAB22-2", category: "Couponing")
AylienCategory.create!(iab: "IAB22-3", category: "Comparison")
AylienCategory.create!(iab: "IAB22-4", category: "Engines")
AylienCategory.create!(iab: "IAB23", category: "Religion & Spirituality")
AylienCategory.create!(iab: "IAB23-1", category: "Alternative Religions")
AylienCategory.create!(iab: "IAB23-2", category: "Atheism/Agnosticism")
AylienCategory.create!(iab: "IAB23-3", category: "Buddhism")
AylienCategory.create!(iab: "IAB23-4", category: "Catholicism")
AylienCategory.create!(iab: "IAB23-5", category: "Christianity")
AylienCategory.create!(iab: "IAB23-6", category: "Hinduism")
AylienCategory.create!(iab: "IAB23-7", category: "Islam")
AylienCategory.create!(iab: "IAB23-8", category: "Judaism")
AylienCategory.create!(iab: "IAB23-9", category: "Latter-Day Saints")
AylienCategory.create!(iab: "IAB23-10", category: "Pagan/Wiccan")
AylienCategory.create!(iab: "IAB24", category: "Uncategorized")
AylienCategory.create!(iab: "IAB25", category: "Non-Standard Content")
AylienCategory.create!(iab: "IAB25-1", category: "Unmoderated UGC")
AylienCategory.create!(iab: "IAB25-2", category: "Extreme Graphic/Explicit Violence")
AylienCategory.create!(iab: "IAB25-3", category: "Pornography")
AylienCategory.create!(iab: "IAB25-4", category: "Profane Content")
AylienCategory.create!(iab: "IAB25-5", category: "Hate Content")
AylienCategory.create!(iab: "IAB25-6", category: "Under Construction")
AylienCategory.create!(iab: "IAB25-7", category: "Incentivized")
AylienCategory.create!(iab: "IAB26", category: "Illegal Content")
AylienCategory.create!(iab: "IAB26-1", category: "Illegal Content")
AylienCategory.create!(iab: "IAB26-2", category: "Warez")
AylienCategory.create!(iab: "IAB26-3", category: "Spyware/Malware")
AylienCategory.create!(iab: "IAB26-4", category: "CopyrightInfringement")

puts "All done!"
